name: Sample-wf
on:
    push:
    branches: ["main"]
  
    workflow_dispatch:

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello, First job executed from Github Actions"
